# Generated by Django 5.0.4 on 2024-04-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_alter_bugreport_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='task',
            field=models.ForeignKey(blank=True, limit_choices_to={'project': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='tasks.project')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='tasks.task'),
        ),
    ]
